/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

 function Ham(props: any) {
    const { nodes, materials } = useGLTF('/models/ham.glb')
    console.log(nodes);
    
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.物体.geometry}
        material={materials.meat}
        position={[-0.163, -1.274, 0.176]}
        scale={[1, 0.728, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.物体001.geometry}
        material={materials.humbug}
        position={[0, -1.095, 0]}
        scale={[1, 0.61, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.平面.geometry}
        material={materials.材质}
        position={[0, 2.253, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.物体002.geometry}
        material={materials.humbug}
        position={[0, 4.823, 0]}
        rotation={[3.129, 0, 0]}
        scale={[1, 0.61, 1]}
      />
    </group>
  )
}

useGLTF.preload('/models/ham.glb')

export default Ham
